name = "childpackages"
description = "To understand child packages"
version = "0.1.0-dev"

authors = ["AyXxos"]
maintainers = ["AyXxos <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://ayxxos.netlify.app"
tags = ["ada", "packages"]

executables = ["childpackages"]
